/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import com.sun.glass.events.KeyEvent;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class acc extends javax.swing.JFrame {
    private String namaAcc, hargaAcc,uang;
    
    /**
     * Creates new form tabel
     */
    public acc() {
        initComponents();
        panel_1.setOpaque(false);
        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        
        int x = layar.width/2-this.getSize().width/2;
        int y = layar.height/2-this.getSize().height/2;
        
        this.setLocation(x,y);
        
    }
    
//    String name, price;
//    public tabel(String tsname, String tsprice){
//        initComponents();
//        this.name= tsname;
//        this.price= tsprice;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrp_acc = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        panel_1 = new javax.swing.JPanel();
        moneyV = new javax.swing.JLabel();
        changeV = new javax.swing.JLabel();
        ChangeValue = new javax.swing.JLabel();
        MoneyValue = new javax.swing.JTextField();
        lbl_teks = new javax.swing.JLabel();
        naruto = new javax.swing.JRadioButton();
        ruby = new javax.swing.JRadioButton();
        minecraft = new javax.swing.JRadioButton();
        luffy = new javax.swing.JRadioButton();
        roblox = new javax.swing.JRadioButton();
        emerald = new javax.swing.JRadioButton();
        snoop = new javax.swing.JRadioButton();
        adamantium = new javax.swing.JRadioButton();
        purrr = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btn_back = new javax.swing.JButton();
        btn_show = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_judul = new javax.swing.JLabel();
        lbl_gmbr1 = new javax.swing.JLabel();
        lbl_gmbr2 = new javax.swing.JLabel();
        lbl_bckG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(null);

        moneyV.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        moneyV.setText("Enter Cash");

        changeV.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        changeV.setText("Change");

        ChangeValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ChangeValue.setText("Your Change");

        MoneyValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MoneyValueKeyTyped(evt);
            }
        });

        lbl_teks.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_teks.setText("Only Accepted $5, $10, $20, $50, $100 Bill");

        btngrp_acc.add(naruto);
        naruto.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        naruto.setText("Naruto Chibi Keychain ($ 25)");

        btngrp_acc.add(ruby);
        ruby.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ruby.setText("Ruby Necklace ($ 90)");

        btngrp_acc.add(minecraft);
        minecraft.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        minecraft.setText("Minecraft Dirt Necklace ($ 55)");

        btngrp_acc.add(luffy);
        luffy.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        luffy.setText("Luffy Chibi Keychain ($ 22)");

        btngrp_acc.add(roblox);
        roblox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        roblox.setText("Roblox Sound Alarm ($ 35)");

        btngrp_acc.add(emerald);
        emerald.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        emerald.setText("Emerald Earring ($ 89)");

        btngrp_acc.add(snoop);
        snoop.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        snoop.setText("Snoop Dogg Necklace ($ 66)");

        btngrp_acc.add(adamantium);
        adamantium.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        adamantium.setText("Adamantium Bullet ($ 95)");

        purrr.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        purrr.setText("PURCHASE");
        purrr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purrrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_1Layout = new javax.swing.GroupLayout(panel_1);
        panel_1.setLayout(panel_1Layout);
        panel_1Layout.setHorizontalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_1Layout.createSequentialGroup()
                        .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_1Layout.createSequentialGroup()
                                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(snoop)
                                    .addComponent(adamantium)
                                    .addComponent(emerald)
                                    .addComponent(minecraft))
                                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(purrr))
                                    .addGroup(panel_1Layout.createSequentialGroup()
                                        .addGap(112, 112, 112)
                                        .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(moneyV)
                                            .addComponent(changeV))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ChangeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(MoneyValue, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(naruto))
                        .addGap(67, 67, 67))
                    .addGroup(panel_1Layout.createSequentialGroup()
                        .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(luffy)
                            .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ruby, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(roblox)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_teks)
                        .addGap(54, 54, 54))))
        );
        panel_1Layout.setVerticalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(naruto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(luffy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ruby)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_1Layout.createSequentialGroup()
                        .addComponent(lbl_teks, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_1Layout.createSequentialGroup()
                        .addComponent(roblox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(moneyV)
                        .addComponent(MoneyValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_1Layout.createSequentialGroup()
                        .addComponent(snoop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adamantium)))
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_1Layout.createSequentialGroup()
                        .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changeV)
                            .addComponent(ChangeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(purrr, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emerald)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minecraft)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        mainPanel.add(panel_1);
        panel_1.setBounds(30, 130, 740, 320);

        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        mainPanel.add(jSeparator1);
        jSeparator1.setBounds(-10, 90, 810, 10);

        btn_back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        mainPanel.add(btn_back);
        btn_back.setBounds(460, 480, 140, 50);

        btn_show.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_show.setText("Main Menu");
        btn_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showActionPerformed(evt);
            }
        });
        mainPanel.add(btn_show);
        btn_show.setBounds(170, 480, 130, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nama", "harga", "uang", "kembali"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        mainPanel.add(jScrollPane1);
        jScrollPane1.setBounds(50, 560, 680, 150);

        lbl_judul.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_judul.setText("Accessories");
        mainPanel.add(lbl_judul);
        lbl_judul.setBounds(0, 20, 800, 50);
        mainPanel.add(lbl_gmbr1);
        lbl_gmbr1.setBounds(70, 10, 100, 80);
        mainPanel.add(lbl_gmbr2);
        lbl_gmbr2.setBounds(640, 10, 100, 80);
        mainPanel.add(lbl_bckG);
        lbl_bckG.setBounds(-180, -30, 1610, 790);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showActionPerformed
       
    }//GEN-LAST:event_btn_showActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        new buy().setVisible(true);
        this.setVisible(false);
    
    }//GEN-LAST:event_btn_backActionPerformed

    private void purrrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purrrActionPerformed
        String tulisan =MoneyValue.getText();
        if(btngrp_acc.isSelected(null) && tulisan.isEmpty() ){
            JOptionPane.showMessageDialog(this, "You Haven't Choose Anything");
        }
        if(btngrp_acc.isSelected(null)==false && tulisan.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Please Enter Your Bill");
        }
        if(btngrp_acc.isSelected(null) && tulisan.isEmpty()== false ){
            JOptionPane.showMessageDialog(this, "Please Choose Item");
        }
        if(btngrp_acc.isSelected(null)==false && tulisan.isEmpty()== false )
        {        
        int money = 0;
        money = Integer.parseInt(MoneyValue.getText());
        int price[]= {25,90,55,22,35,90,66,95};
        
        {
        if(money == 5||money == 10||money == 20||money == 50||money == 100){
         if (naruto.isSelected()){
                namaAcc = "Naruto Chibi Keychain";
                hargaAcc = "25";
                uang = MoneyValue.getText();
                money = money - (price[0]);
        }else if (ruby.isSelected()){
                namaAcc = "Ruby Necklace";
                hargaAcc = "90";
                uang = MoneyValue.getText();
                money = money - (price[1]);
        }else if (minecraft.isSelected()){
                namaAcc = "Minecraft Dirt Necklace";
                hargaAcc = "55";
                uang = MoneyValue.getText();
                money = money - (price[2]);
        }else if (luffy.isSelected()){
                namaAcc = "Luffy Chibi Keychain";
                hargaAcc = "22";
                uang = MoneyValue.getText();
                money = money - (price[3]);
        }else if (roblox.isSelected()){
                namaAcc = "Roblox Sound Alarm";
                hargaAcc = "35";
                uang = MoneyValue.getText();
                money = money - (price[4]);
        }else if (emerald.isSelected()){
                namaAcc = "Emerald Earring";
                hargaAcc = "90";
                uang = MoneyValue.getText();
                money = money - (price[5]);
        }else if (snoop.isSelected()){
                namaAcc = "Snoop Dogg Necklace";
                hargaAcc = "66";
                uang = MoneyValue.getText();
                money = money - (price[6]);
        }else if (adamantium.isSelected()){
                namaAcc = "Adamantium Bullet";
                hargaAcc= "95";
                uang = MoneyValue.getText();
                money = money - (price[7]);
        }
        
            
            if (money < 0){
                JOptionPane.showMessageDialog(this,"The Entered Money is Not Enough!!" );
                MoneyValue.setText(null);
            }
            else
            {
                ChangeValue.setText("$ "+Integer.toString(money));
                
                    DefaultTableModel datauser = (DefaultTableModel) jTable1.getModel();
                    List ls = new ArrayList<>();
                    ls.add(namaAcc);
                    ls.add(hargaAcc);
                    ls.add(uang);
                    ls.add(money);
                    datauser.addRow(ls.toArray());
                
                int response = JOptionPane.showConfirmDialog(null, "Thank you for purchasing, do you want to purchase again?", "Item Purchased",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (response == JOptionPane.YES_OPTION) {
                    MoneyValue.setText(null);
                    ChangeValue.setText("Your Change");
                }else{
                    new mainMenu().setVisible(true);
                    this.setVisible(false);
                }
            } 
            }else{
             JOptionPane.showMessageDialog(this, "Please Enter the Correct Money");
             MoneyValue.setText(null);
            }
        }
        
        }
        
        
    }//GEN-LAST:event_purrrActionPerformed

    private void MoneyValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MoneyValueKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_MoneyValueKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChangeValue;
    private javax.swing.JTextField MoneyValue;
    private javax.swing.JRadioButton adamantium;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_show;
    private javax.swing.ButtonGroup btngrp_acc;
    private javax.swing.JLabel changeV;
    private javax.swing.JRadioButton emerald;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_bckG;
    private javax.swing.JLabel lbl_gmbr1;
    private javax.swing.JLabel lbl_gmbr2;
    private javax.swing.JLabel lbl_judul;
    private javax.swing.JLabel lbl_teks;
    private javax.swing.JRadioButton luffy;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton minecraft;
    private javax.swing.JLabel moneyV;
    private javax.swing.JRadioButton naruto;
    private javax.swing.JPanel panel_1;
    private javax.swing.JButton purrr;
    private javax.swing.JRadioButton roblox;
    private javax.swing.JRadioButton ruby;
    private javax.swing.JRadioButton snoop;
    // End of variables declaration//GEN-END:variables
}

