/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author user
 */
public class buy extends javax.swing.JFrame {

    /**
     * Creates new form buy
     */
    public buy() {
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        
        int x = layar.width/2-this.getSize().width/2;
        int y = layar.height/2-this.getSize().height/2;
        
        this.setLocation(x,y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_buyMenu = new javax.swing.JLabel();
        btn_food = new javax.swing.JButton();
        btn_drinks = new javax.swing.JButton();
        btn_buyBack = new javax.swing.JButton();
        btn_acc = new javax.swing.JButton();
        gmbr = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_text = new javax.swing.JLabel();
        lbl_bckG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        lbl_buyMenu.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_buyMenu.setText("Buy Menu");
        jPanel1.add(lbl_buyMenu);
        lbl_buyMenu.setBounds(14, 15, 229, 80);

        btn_food.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_food.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\project\\src\\project\\gambar\\icons8-potato-chips-80.png")); // NOI18N
        btn_food.setText("Snacks");
        btn_food.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_food.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_food.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_foodActionPerformed(evt);
            }
        });
        jPanel1.add(btn_food);
        btn_food.setBounds(20, 220, 161, 140);

        btn_drinks.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_drinks.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\project\\src\\project\\gambar\\icons8-beer-can-80.png")); // NOI18N
        btn_drinks.setText("Drinks");
        btn_drinks.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_drinks.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_drinks.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_drinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_drinksActionPerformed(evt);
            }
        });
        jPanel1.add(btn_drinks);
        btn_drinks.setBounds(200, 220, 161, 140);

        btn_buyBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_buyBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\project\\src\\project\\gambar\\icons8-go-back-32.png")); // NOI18N
        btn_buyBack.setText("   Back");
        btn_buyBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buyBackActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buyBack);
        btn_buyBack.setBounds(414, 463, 141, 41);

        btn_acc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_acc.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\project\\src\\project\\gambar\\icons8-sailor-moon-80.png")); // NOI18N
        btn_acc.setText("Accessories");
        btn_acc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_acc.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_acc.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_acc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accActionPerformed(evt);
            }
        });
        jPanel1.add(btn_acc);
        btn_acc.setBounds(380, 220, 200, 140);
        jPanel1.add(gmbr);
        gmbr.setBounds(250, 2, 105, 109);

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(-6, 124, 610, 10);

        lbl_text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_text.setText("What Would You Buy ??");
        jPanel1.add(lbl_text);
        lbl_text.setBounds(188, 152, 193, 22);

        lbl_bckG.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\project\\src\\project\\gambar\\49c58PICbXnz55UufmD59_PIC2018.jpg")); // NOI18N
        jPanel1.add(lbl_bckG);
        lbl_bckG.setBounds(-50, -20, 690, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_foodActionPerformed
        // TODO add your handling code here:
        
        new snacks().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_foodActionPerformed

    private void btn_drinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_drinksActionPerformed
        // TODO add your handling code here:
        
        new drinks().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_drinksActionPerformed

    private void btn_buyBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buyBackActionPerformed
        // TODO add your handling code here:
        
        new mainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_buyBackActionPerformed

    private void btn_accActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accActionPerformed
        // TODO add your handling code here:
        
        new acc().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_accActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acc;
    private javax.swing.JButton btn_buyBack;
    private javax.swing.JButton btn_drinks;
    private javax.swing.JButton btn_food;
    private javax.swing.JLabel gmbr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_bckG;
    private javax.swing.JLabel lbl_buyMenu;
    private javax.swing.JLabel lbl_text;
    // End of variables declaration//GEN-END:variables
}
