/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import com.sun.glass.events.KeyEvent;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class drinks extends javax.swing.JFrame {
//    ArrayList<show> lihat;
//    String header[] = new String[]{
//        "nama","harga"
//    };
//    DefaultTableModel dtm;
//    int row, col;
    
//    setterget sg =  new setterget();
//    seget dr =new seget();
//    
    String nameDrinks, nama, uang;
    String harga,hargaDrink;
//
//    public String getNama() {
//        return nama;
//    }
//
//    public void setNama(String nama) {
//        this.nama = nama;
//    }
//
//    public String getHarga() {
//        return harga;
//    }
//
//    public void setHarga(String harga) {
//        this.harga = harga;
//    }
//    
    

    /**
     * Creates new form drinks
     */
    public drinks() {
        initComponents();
//        lihat = new ArrayList<>();
//        dtm = new DefaultTableModel(header,0);
//        jTable1.setModel(dtm);
        
        panel_1.setOpaque(false);
        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        
        int x = layar.width/2-this.getSize().width/2;
        int y = layar.height/2-this.getSize().height/2;
        
        this.setLocation(x,y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupDrinks = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        gmbr1 = new javax.swing.JLabel();
        gmbr2 = new javax.swing.JLabel();
        lbl_judul = new javax.swing.JLabel();
        panel_1 = new javax.swing.JPanel();
        negroni = new javax.swing.JRadioButton();
        whiskey = new javax.swing.JRadioButton();
        jd = new javax.swing.JRadioButton();
        martini = new javax.swing.JRadioButton();
        energy = new javax.swing.JRadioButton();
        margarita = new javax.swing.JRadioButton();
        cendol = new javax.swing.JRadioButton();
        minerale = new javax.swing.JRadioButton();
        moneyV = new javax.swing.JLabel();
        changeV = new javax.swing.JLabel();
        MoneyValue = new javax.swing.JTextField();
        Purchase = new javax.swing.JButton();
        ChangeValue = new javax.swing.JLabel();
        lbl_txt = new javax.swing.JLabel();
        btn_mainMenu = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_bckG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(null);

        gmbr1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\project\\src\\project\\gambar\\icons8-bar-filled-50.png")); // NOI18N
        mainPanel.add(gmbr1);
        gmbr1.setBounds(81, 33, 58, 100);

        gmbr2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\project\\src\\project\\gambar\\icons8-drink-filled-50.png")); // NOI18N
        mainPanel.add(gmbr2);
        gmbr2.setBounds(740, 30, 70, 102);

        lbl_judul.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_judul.setText("Drinks");
        mainPanel.add(lbl_judul);
        lbl_judul.setBounds(-2, 54, 860, 44);

        panel_1.setBackground(new java.awt.Color(255, 255, 255));
        panel_1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        btnGroupDrinks.add(negroni);
        negroni.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        negroni.setText("Negroni ($ 6)");
        negroni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negroniActionPerformed(evt);
            }
        });

        btnGroupDrinks.add(whiskey);
        whiskey.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        whiskey.setText("Whiskey ($ 6)");
        whiskey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiskeyActionPerformed(evt);
            }
        });

        btnGroupDrinks.add(jd);
        jd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jd.setText("JD ($ 5)");
        jd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdActionPerformed(evt);
            }
        });

        btnGroupDrinks.add(martini);
        martini.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        martini.setText("Martini ($ 6)");
        martini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                martiniActionPerformed(evt);
            }
        });

        btnGroupDrinks.add(energy);
        energy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        energy.setText("GeForce Energy ($ 7)");
        energy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                energyActionPerformed(evt);
            }
        });

        btnGroupDrinks.add(margarita);
        margarita.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        margarita.setText("Margarita ($ 5)");
        margarita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                margaritaActionPerformed(evt);
            }
        });

        btnGroupDrinks.add(cendol);
        cendol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cendol.setText("Cendol ($ 5)");
        cendol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cendolActionPerformed(evt);
            }
        });

        btnGroupDrinks.add(minerale);
        minerale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        minerale.setText("Minerale ($ 9)");
        minerale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mineraleActionPerformed(evt);
            }
        });

        moneyV.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        moneyV.setText("Enter Cash");

        changeV.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        changeV.setText("Change");

        MoneyValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoneyValueActionPerformed(evt);
            }
        });
        MoneyValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MoneyValueKeyTyped(evt);
            }
        });

        Purchase.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Purchase.setText("PURCHASE");
        Purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseActionPerformed(evt);
            }
        });

        ChangeValue.setBackground(new java.awt.Color(153, 153, 153));
        ChangeValue.setText("Your Change");

        lbl_txt.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbl_txt.setText("Only Accepted $5, $10, $20, $50, $100 Bill");

        javax.swing.GroupLayout panel_1Layout = new javax.swing.GroupLayout(panel_1);
        panel_1.setLayout(panel_1Layout);
        panel_1Layout.setHorizontalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(negroni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cendol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(energy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minerale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(margarita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(martini, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(whiskey, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_1Layout.createSequentialGroup()
                        .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changeV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(moneyV, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MoneyValue, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(ChangeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_1Layout.createSequentialGroup()
                        .addComponent(lbl_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Purchase)
                .addGap(78, 78, 78))
        );
        panel_1Layout.setVerticalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_1Layout.createSequentialGroup()
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(lbl_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(moneyV)
                            .addComponent(MoneyValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changeV)
                            .addComponent(ChangeValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panel_1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(negroni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(whiskey)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(martini)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(margarita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(energy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cendol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minerale)
                        .addGap(17, 17, 17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Purchase)
                .addContainerGap())
        );

        mainPanel.add(panel_1);
        panel_1.setBounds(60, 170, 700, 318);

        btn_mainMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_mainMenu.setText("Main Menu");
        btn_mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mainMenuActionPerformed(evt);
            }
        });
        mainPanel.add(btn_mainMenu);
        btn_mainMenu.setBounds(175, 510, 160, 50);

        btn_back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_back.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\project\\src\\project\\gambar\\icons8-go-back-32.png")); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        mainPanel.add(btn_back);
        btn_back.setBounds(530, 510, 160, 50);

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        mainPanel.add(jSeparator1);
        jSeparator1.setBounds(0, 122, 860, 10);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nama", "harga", "uang", "kembali"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        mainPanel.add(jScrollPane1);
        jScrollPane1.setBounds(40, 595, 790, 130);

        lbl_bckG.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\project\\src\\project\\gambar\\49c58PICbXnz55UufmD59_PIC2018.jpg")); // NOI18N
        mainPanel.add(lbl_bckG);
        lbl_bckG.setBounds(-100, -30, 1100, 790);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void negroniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negroniActionPerformed
      
    }//GEN-LAST:event_negroniActionPerformed
    
    private void whiskeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiskeyActionPerformed
     
    }//GEN-LAST:event_whiskeyActionPerformed
    
    private void jdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdActionPerformed
    
    }//GEN-LAST:event_jdActionPerformed
    
    private void martiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_martiniActionPerformed
       
    }//GEN-LAST:event_martiniActionPerformed
    
    private void energyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_energyActionPerformed
      
    }//GEN-LAST:event_energyActionPerformed
    
    private void margaritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_margaritaActionPerformed
        
    }//GEN-LAST:event_margaritaActionPerformed
    
    private void cendolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cendolActionPerformed
       
    }//GEN-LAST:event_cendolActionPerformed
    
    private void mineraleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mineraleActionPerformed
        
    }//GEN-LAST:event_mineraleActionPerformed
    
    private void btn_mainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mainMenuActionPerformed
        // TODO add your handling code here:
        
        new mainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_mainMenuActionPerformed

    private void MoneyValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoneyValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoneyValueActionPerformed

    private void PurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseActionPerformed
        String tulisan =MoneyValue.getText();
        if(btnGroupDrinks.isSelected(null) && tulisan.isEmpty() ){
            JOptionPane.showMessageDialog(this, "You Haven't Choose Anything");
        }
        if(btnGroupDrinks.isSelected(null)==false && tulisan.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Please Enter Your Bill");
        }
        if(btnGroupDrinks.isSelected(null) && tulisan.isEmpty()== false ){
            JOptionPane.showMessageDialog(this, "Please Choose Item");
        }
        if(btnGroupDrinks.isSelected(null)==false && tulisan.isEmpty()== false )
        
        {    
        int money = 0;
        money = Integer.parseInt(MoneyValue.getText());
        int price[]= {6,6,5,6,7,5,5,9};
        
        
        {
            if(money == 5||money == 10||money == 20||money == 50||money == 100)
            {    
            if (negroni.isSelected()){
                nameDrinks = "Negroni";
                hargaDrink = "6";
                uang = MoneyValue.getText();
                money = money - (price[0]);
        }else if (whiskey.isSelected()){
                nameDrinks = "Whiskey";
                hargaDrink = "6";
                uang = MoneyValue.getText();
                money = money - (price[1]);
        }else if (jd.isSelected()){
                nameDrinks = "J D";
                hargaDrink = "5";
                uang = MoneyValue.getText();
                money = money - (price[2]);
        }else if (martini.isSelected()){
                nameDrinks = "Martini";
                hargaDrink = "6";
                uang = MoneyValue.getText();
                uang = MoneyValue.getText();
                money = money - (price[3]);
        }else if (energy.isSelected()){
                nameDrinks = "Ge Force Energy Drink";
                hargaDrink = "7";
                uang = MoneyValue.getText();
                money = money - (price[4]);
        }else if (margarita.isSelected()){
                nameDrinks = "Margarita";
                hargaDrink = "5";
                uang = MoneyValue.getText();
                money = money - (price[5]);
        }else if (cendol.isSelected()){
                nameDrinks = "Cendol";
                hargaDrink = "5";
                uang = MoneyValue.getText();
                money = money - (price[6]);
        }else if (minerale.isSelected()){
                nameDrinks = "Le Minerale";
                hargaDrink = "9";
                uang = MoneyValue.getText();
                money = money - (price[7]);
            }
            //bawah kodingan faris
//            lihat.add(new show(nama, harga));
//            dtm.setRowCount(0);
//            for(int i=0; i<lihat.size(); i++){
//            Object []objs={
//             lihat.get(i).nama
//            };
//            dtm.addRow(objs);
//            }
        
            
            if (money < 0){
                JOptionPane.showMessageDialog(this,"The Entered Money is Not Enough!!" );
                MoneyValue.setText(null);
            }
            else
            {
                ChangeValue.setText("$ "+Integer.toString(money));
                
                DefaultTableModel datauser = (DefaultTableModel) jTable1.getModel();
                List ls = new ArrayList<>();
                ls.add(nameDrinks);
                ls.add(hargaDrink);
                ls.add(uang);
                ls.add(money);
                datauser.addRow(ls.toArray());
                
                int response = JOptionPane.showConfirmDialog(null, "Thank you for purchasing, do you want to purchase again?", "Item Purchased",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (response == JOptionPane.YES_OPTION) {
                    MoneyValue.setText(null);
                    ChangeValue.setText("Your Change");
                }else{
                    new mainMenu().setVisible(true);
                    this.setVisible(false);
                }
            } 
            }else{
             JOptionPane.showMessageDialog(this, "Please Enter the Correct Money");
             MoneyValue.setText(null);
            }
        }
        }
        
        
    
        
                
    }//GEN-LAST:event_PurchaseActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        
        new buy().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void MoneyValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MoneyValueKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_MoneyValueKeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(drinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new drinks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChangeValue;
    private javax.swing.JTextField MoneyValue;
    private javax.swing.JButton Purchase;
    private javax.swing.ButtonGroup btnGroupDrinks;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_mainMenu;
    private javax.swing.JRadioButton cendol;
    private javax.swing.JLabel changeV;
    private javax.swing.JRadioButton energy;
    private javax.swing.JLabel gmbr1;
    private javax.swing.JLabel gmbr2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton jd;
    private javax.swing.JLabel lbl_bckG;
    private javax.swing.JLabel lbl_judul;
    private javax.swing.JLabel lbl_txt;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton margarita;
    private javax.swing.JRadioButton martini;
    private javax.swing.JRadioButton minerale;
    private javax.swing.JLabel moneyV;
    private javax.swing.JRadioButton negroni;
    private javax.swing.JPanel panel_1;
    private javax.swing.JRadioButton whiskey;
    // End of variables declaration//GEN-END:variables
}
