/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        
        int x = layar.width/2-this.getSize().width/2;
        int y = layar.height/2-this.getSize().height/2;
        
        this.setLocation(x,y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        lbl_judul = new javax.swing.JLabel();
        btn_buy = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_txt = new javax.swing.JLabel();
        lbl_bckG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mainPanel.setLayout(null);

        lbl_judul.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 36)); // NOI18N
        lbl_judul.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\project\\src\\project\\gambar\\icons8-vending-machine-100.png")); // NOI18N
        lbl_judul.setText("Chit Chat Vending Machine");
        mainPanel.add(lbl_judul);
        lbl_judul.setBounds(14, 15, 678, 111);

        btn_buy.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_buy.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\project\\src\\project\\gambar\\icons8-buy-80 2.png")); // NOI18N
        btn_buy.setText("Buy");
        btn_buy.setBorder(null);
        btn_buy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_buy.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_buy.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buyActionPerformed(evt);
            }
        });
        mainPanel.add(btn_buy);
        btn_buy.setBounds(159, 230, 113, 137);

        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\project\\src\\project\\gambar\\icons8-close-window-80.png")); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.setBorder(null);
        btn_exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_exit.setMaximumSize(new java.awt.Dimension(81, 219));
        btn_exit.setMinimumSize(new java.awt.Dimension(81, 219));
        btn_exit.setPreferredSize(new java.awt.Dimension(81, 219));
        btn_exit.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btn_exit.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        mainPanel.add(btn_exit);
        btn_exit.setBounds(441, 230, 120, 140);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        mainPanel.add(jSeparator1);
        jSeparator1.setBounds(-6, 133, 740, 10);

        lbl_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_txt.setText("Welcome to Chit Chat Vending Machine.       Please Choose the Button Below");
        mainPanel.add(lbl_txt);
        lbl_txt.setBounds(44, 150, 615, 22);

        lbl_bckG.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\project\\src\\project\\gambar\\17658PIC7AcUfmIeb5de7_PIC2018.jpg")); // NOI18N
        lbl_bckG.setText("jLabel1");
        mainPanel.add(lbl_bckG);
        lbl_bckG.setBounds(-190, 0, 990, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buyActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        
        poli1 ijat[]=new poli1[1];
        ijat[0]=new poli2();
        
        for (int x=0;x<1;++x){
            ijat[x].mm();
        }
        
    }//GEN-LAST:event_btn_buyActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showOptionDialog(this, 
                "Are You Sure Want to Exit ?", "Exit", 
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, 
                null, null, null);
        
        if(exit == JOptionPane.YES_NO_OPTION){
            String saran = JOptionPane.showInputDialog("Please enter your advice for us");
            JOptionPane.showMessageDialog(null, 
            "Thank you, have a nice day");
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buy;
    private javax.swing.JButton btn_exit;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_bckG;
    private javax.swing.JLabel lbl_judul;
    private javax.swing.JLabel lbl_txt;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
