/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import com.sun.glass.events.KeyEvent;
import java.awt.Dimension;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class snacks extends javax.swing.JFrame {
    private String uang, namaFood, hargaFood;

    /**
     * Creates new form snacks
     */
    public snacks() {
        initComponents();
        
        //panel_1.setBackground(new Color (1,0,0,2));
        panel_1.setOpaque(false);
        
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        
        int x = layar.width/2-this.getSize().width/2;
        int y = layar.height/2-this.getSize().height/2;
        
        this.setLocation(x,y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSnack = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        gmbr1 = new javax.swing.JLabel();
        gmbr2 = new javax.swing.JLabel();
        lbl_Snacks = new javax.swing.JLabel();
        panel_1 = new javax.swing.JPanel();
        chobro = new javax.swing.JRadioButton();
        chebar = new javax.swing.JRadioButton();
        chocoo = new javax.swing.JRadioButton();
        nutbro = new javax.swing.JRadioButton();
        nutbar = new javax.swing.JRadioButton();
        snibar = new javax.swing.JRadioButton();
        blubar = new javax.swing.JRadioButton();
        pinpiz = new javax.swing.JRadioButton();
        moneyV = new javax.swing.JLabel();
        changeV = new javax.swing.JLabel();
        Purchase = new javax.swing.JButton();
        MoneyValue = new javax.swing.JTextField();
        ChangeValue = new javax.swing.JLabel();
        lbl_text = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_mainMenu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbl_bckG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(null);

        gmbr1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\project\\src\\project\\gambar\\icons8-potato-chips-80.png")); // NOI18N
        mainPanel.add(gmbr1);
        gmbr1.setBounds(60, 40, 90, 90);

        gmbr2.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\project\\src\\project\\gambar\\icons8-pizza-80.png")); // NOI18N
        mainPanel.add(gmbr2);
        gmbr2.setBounds(730, 40, 90, 80);

        lbl_Snacks.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_Snacks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Snacks.setText("Snack");
        mainPanel.add(lbl_Snacks);
        lbl_Snacks.setBounds(-2, 60, 900, 44);

        panel_1.setBackground(new java.awt.Color(255, 255, 255));

        btnGroupSnack.add(chobro);
        chobro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chobro.setText("Choco Brownies ($ 8)");
        chobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chobroActionPerformed(evt);
            }
        });

        btnGroupSnack.add(chebar);
        chebar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chebar.setText("Cheese Cake Bars ($ 7)");
        chebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chebarActionPerformed(evt);
            }
        });

        btnGroupSnack.add(chocoo);
        chocoo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chocoo.setText("Choco Cookies ($ 5)");
        chocoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chocooActionPerformed(evt);
            }
        });

        btnGroupSnack.add(nutbro);
        nutbro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nutbro.setText("Nuttela Brownies ($ 9)");
        nutbro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutbroActionPerformed(evt);
            }
        });

        btnGroupSnack.add(nutbar);
        nutbar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nutbar.setText("Nuttela Bars ($ 9)");
        nutbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutbarActionPerformed(evt);
            }
        });

        btnGroupSnack.add(snibar);
        snibar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        snibar.setText("Snicker Bars ($ 5)");
        snibar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snibarActionPerformed(evt);
            }
        });

        btnGroupSnack.add(blubar);
        blubar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        blubar.setText("Blueberry Bars ($ 6)");
        blubar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blubarActionPerformed(evt);
            }
        });

        btnGroupSnack.add(pinpiz);
        pinpiz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pinpiz.setText("Pineapple Pizza ($ 9)");
        pinpiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinpizActionPerformed(evt);
            }
        });

        moneyV.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        moneyV.setText("Enter Cash");

        changeV.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        changeV.setText("Change");

        Purchase.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Purchase.setText("PURCHASE");
        Purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseActionPerformed(evt);
            }
        });

        MoneyValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoneyValueActionPerformed(evt);
            }
        });
        MoneyValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                MoneyValueKeyTyped(evt);
            }
        });

        ChangeValue.setText("Your Change");

        lbl_text.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lbl_text.setText("Only Accepted $5, $10, $20, $50, $100 Bill");

        javax.swing.GroupLayout panel_1Layout = new javax.swing.GroupLayout(panel_1);
        panel_1.setLayout(panel_1Layout);
        panel_1Layout.setHorizontalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Purchase)
                .addGap(79, 79, 79))
            .addGroup(panel_1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_1Layout.createSequentialGroup()
                        .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pinpiz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(blubar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(111, 111, 111)
                        .addComponent(lbl_text)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_1Layout.createSequentialGroup()
                        .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(snibar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel_1Layout.createSequentialGroup()
                                .addComponent(nutbro)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changeV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(moneyV, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MoneyValue, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(ChangeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_1Layout.createSequentialGroup()
                        .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nutbar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chocoo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chobro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chebar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel_1Layout.setVerticalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(chobro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chebar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chocoo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nutbar)
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blubar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_1Layout.createSequentialGroup()
                                .addComponent(pinpiz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(snibar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nutbro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_1Layout.createSequentialGroup()
                                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(moneyV)
                                    .addComponent(MoneyValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(changeV, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ChangeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)))
                        .addComponent(Purchase)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_text)
                        .addGap(129, 129, 129))))
        );

        mainPanel.add(panel_1);
        panel_1.setBounds(90, 210, 700, 320);

        btn_back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_back.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\project\\src\\project\\gambar\\icons8-go-back-32.png")); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        mainPanel.add(btn_back);
        btn_back.setBounds(520, 540, 130, 50);

        btn_mainMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_mainMenu.setText("Main Menu");
        btn_mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mainMenuActionPerformed(evt);
            }
        });
        mainPanel.add(btn_mainMenu);
        btn_mainMenu.setBounds(250, 540, 140, 50);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 51));
        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        mainPanel.add(jSeparator1);
        jSeparator1.setBounds(0, 150, 900, 10);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Harga", "uang", "kembali"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        mainPanel.add(jScrollPane1);
        jScrollPane1.setBounds(100, 610, 670, 160);

        lbl_bckG.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\project\\src\\project\\gambar\\49c58PICbXnz55UufmD59_PIC2018.jpg")); // NOI18N
        lbl_bckG.setText("jLabel1");
        mainPanel.add(lbl_bckG);
        lbl_bckG.setBounds(-90, -20, 1030, 890);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pinpizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinpizActionPerformed
           
    }//GEN-LAST:event_pinpizActionPerformed
    
    private void blubarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blubarActionPerformed
           
    }//GEN-LAST:event_blubarActionPerformed
    
    private void snibarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snibarActionPerformed
          
    }//GEN-LAST:event_snibarActionPerformed
    
    private void nutbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutbarActionPerformed
          
    }//GEN-LAST:event_nutbarActionPerformed
    
    private void nutbroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutbroActionPerformed
            
    }//GEN-LAST:event_nutbroActionPerformed
    
    private void chocooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chocooActionPerformed
          
    }//GEN-LAST:event_chocooActionPerformed
    
    private void chebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chebarActionPerformed
         
    }//GEN-LAST:event_chebarActionPerformed
    
    private void chobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chobroActionPerformed

    }//GEN-LAST:event_chobroActionPerformed

    private void MoneyValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoneyValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MoneyValueActionPerformed

    private void PurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseActionPerformed
      String tulisan =MoneyValue.getText();
        if(btnGroupSnack.isSelected(null) && tulisan.isEmpty() ){
            JOptionPane.showMessageDialog(this, "You Haven't Choose Anything");
        }
        if(btnGroupSnack.isSelected(null)==false && tulisan.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Please Enter Your Bill");
        }
        if(btnGroupSnack.isSelected(null) && tulisan.isEmpty()== false ){
            JOptionPane.showMessageDialog(this, "Please Choose Item");
        }
        if(btnGroupSnack.isSelected(null)==false && tulisan.isEmpty()== false )
        
        {
            
        int money = 0;
        money = Integer.parseInt(MoneyValue.getText());
        int price[]= {8,7,5,9,9,5,6,9};   
        
        if(money == 5||money == 10||money == 20||money == 50||money == 100){
            
         if (chobro.isSelected()){
                namaFood = "Choco Brownies";
                hargaFood = "8";
                uang = MoneyValue.getText();
                money = money - (price[0]);
        }else if (chebar.isSelected()){
                namaFood = "Cheese Cake Bars";
                hargaFood = "7";
                uang = MoneyValue.getText();
                money = money - (price[1]);
        }else if (chocoo.isSelected()){
                namaFood = "Choco Cookies";
                hargaFood = "5";
                uang = MoneyValue.getText();
                money = money - (price[2]);
        }else if (nutbro.isSelected()){
                namaFood = "Nutella brownies";
                hargaFood = "9";
                uang = MoneyValue.getText();
                money = money - (price[3]);
        }else if (nutbar.isSelected()){
                namaFood = "Nutella Bars";
                hargaFood = "9";
                uang = MoneyValue.getText();
                money = money - (price[4]);
        }else if (snibar.isSelected()){
                namaFood = "snickers bars";
                hargaFood = "5";
                uang = MoneyValue.getText();
                money = money - (price[5]);
        }else if (blubar.isSelected()){
                namaFood = "blueberry bars";
                hargaFood = "6";
                uang = MoneyValue.getText();
                money = money - (price[6]);
        }else if (pinpiz.isSelected()){
                namaFood = "pineapple pizza";
                hargaFood = "9";
                uang = MoneyValue.getText();
                money = money - (price[7]);
        }
        
        
            if (money < 0){
                JOptionPane.showMessageDialog(rootPane,"The Entered Money is Not Enough!!" );
                MoneyValue.setText(null);
            }
            else
            {
                ChangeValue.setText("$ "+Integer.toString(money));
                
                    DefaultTableModel datauser = (DefaultTableModel) jTable1.getModel();
                    List ls = new ArrayList<>();
                    ls.add(namaFood);
                    ls.add(hargaFood);
                    ls.add(uang);
                    ls.add(money);
                    datauser.addRow(ls.toArray());
                
                int response = JOptionPane.showConfirmDialog(null, "Thank you for purchasing, do you want to purchase again?", "Item Purchased",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (response == JOptionPane.YES_OPTION) {
                    MoneyValue.setText(null);
                    ChangeValue.setText("Your Change");
                }else{
                    new mainMenu().setVisible(true);
                    this.setVisible(false);
                }   
            }     
        }else
        {
            JOptionPane.showMessageDialog(this, "Please Enter the Correct Money");
            MoneyValue.setText(null);
        }
        
        }
                  
    }//GEN-LAST:event_PurchaseActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        
        new buy().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_mainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mainMenuActionPerformed
        // TODO add your handling code here:
        
        new mainMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_mainMenuActionPerformed

    private void MoneyValueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MoneyValueKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||c==KeyEvent.VK_DELETE))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_MoneyValueKeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(snacks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(snacks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(snacks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(snacks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new snacks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChangeValue;
    private javax.swing.JTextField MoneyValue;
    private javax.swing.JButton Purchase;
    private javax.swing.JRadioButton blubar;
    private javax.swing.ButtonGroup btnGroupSnack;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_mainMenu;
    private javax.swing.JLabel changeV;
    private javax.swing.JRadioButton chebar;
    private javax.swing.JRadioButton chobro;
    private javax.swing.JRadioButton chocoo;
    private javax.swing.JLabel gmbr1;
    private javax.swing.JLabel gmbr2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_Snacks;
    private javax.swing.JLabel lbl_bckG;
    private javax.swing.JLabel lbl_text;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel moneyV;
    private javax.swing.JRadioButton nutbar;
    private javax.swing.JRadioButton nutbro;
    private javax.swing.JPanel panel_1;
    private javax.swing.JRadioButton pinpiz;
    private javax.swing.JRadioButton snibar;
    // End of variables declaration//GEN-END:variables
}
